# Generated by Django 6.0 on 2026-01-02 22:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_team_projects_teammember_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=app.models.generate_unique_id, max_length=50),
        ),
    ]
